-- Run this once if your Supabase database already exists.
-- It stores Telegram users and their phone number after they share it once.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id text not null unique,
  username text,
  first_name text,
  phone_number text,
  phone_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_users_telegram_id
on public.users (telegram_id);
