PRODUCTS = [
    {
        "id": "prod-1",
        "name": "Horizon Elite 75% Mechanical Keyboard",
        "description": "Compact hot-swappable mechanical keyboard with PBT keycaps and RGB lighting.",
        "price": 149,
        "category": "keyboards",
        "imageUrl": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&auto=format&fit=crop&q=80",
        "stock": 12,
    },
    {
        "id": "prod-2",
        "name": "AeroStream Wireless Gaming Mouse",
        "description": "Ultra-lightweight wireless mouse with high-precision optical sensor.",
        "price": 89,
        "category": "mice",
        "imageUrl": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400&auto=format&fit=crop&q=80",
        "stock": 25,
    },
    {
        "id": "prod-3",
        "name": "Ultra-Wide RGB Desk Mouse Pad",
        "description": "Large smooth tracking surface with stitched edges and RGB lighting.",
        "price": 39,
        "category": "mouse-pads",
        "imageUrl": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&auto=format&fit=crop&q=80",
        "stock": 31,
    },
    {
        "id": "prod-4",
        "name": "Coiled Aviator Keyboard Cable",
        "description": "Detachable braided USB-C cable designed for custom mechanical keyboards.",
        "price": 32,
        "category": "cables-hubs",
        "imageUrl": "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=400&auto=format&fit=crop&q=80",
        "stock": 50,
    },
    {
        "id": "prod-5",
        "name": "Minimalist Monitor Riser Stand",
        "description": "Wooden monitor stand with space for keyboard storage and desk organization.",
        "price": 110,
        "category": "monitor-accessories",
        "imageUrl": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&auto=format&fit=crop&q=80",
        "stock": 6,
    },
    {
        "id": "prod-6",
        "name": "USB-C Multiport Hub",
        "description": "Compact hub with HDMI, USB-A, USB-C PD, SD card reader, and Ethernet.",
        "price": 59,
        "category": "cables-hubs",
        "imageUrl": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&auto=format&fit=crop&q=80",
        "stock": 28,
    },
    {
        "id": "prod-7",
        "name": "Retro Dolch PBT Keycap Set",
        "description": "Durable PBT keycaps with clean legends for most mechanical keyboard layouts.",
        "price": 65,
        "category": "keyboards",
        "imageUrl": "https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?w=400&auto=format&fit=crop&q=80",
        "stock": 14,
    },
    {
        "id": "prod-8",
        "name": "Precision Ergonomic Vertical Mouse",
        "description": "Comfortable vertical mouse designed to reduce wrist strain during long work hours.",
        "price": 79,
        "category": "mice",
        "imageUrl": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&auto=format&fit=crop&q=80",
        "stock": 19,
    },
    {
        "id": "prod-9",
        "name": "Carbon Custom Macro Pad",
        "description": "Programmable 12-key hot-swappable macro pad with dual rotary knobs.",
        "price": 55,
        "category": "keyboards",
        "imageUrl": "https://images.unsplash.com/photo-1595225476474-87563907a212?w=400&auto=format&fit=crop&q=80",
        "stock": 22,
    },
    {
        "id": "prod-10",
        "name": "4K USB Webcam",
        "description": "Sharp 4K webcam with autofocus, privacy cover, and built-in noise reduction mic.",
        "price": 99,
        "category": "webcams-mics",
        "imageUrl": "https://images.unsplash.com/photo-1611174743420-3d7df880ce32?w=400&auto=format&fit=crop&q=80",
        "stock": 18,
    },
    {
        "id": "prod-11",
        "name": "Quantum RGB Wireless Mouse",
        "description": "Dual-mode wireless mouse with customizable buttons and RGB lighting.",
        "price": 115,
        "category": "mice",
        "imageUrl": "https://images.unsplash.com/photo-1625600243103-1dc6824c6c8a?w=400&auto=format&fit=crop&q=80",
        "stock": 17,
    },
    {
        "id": "prod-12",
        "name": "Alcantara Keyboard Wrist Rest",
        "description": "Soft memory foam wrist rest for comfortable typing and gaming sessions.",
        "price": 35,
        "category": "desk-setup",
        "imageUrl": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&auto=format&fit=crop&q=80",
        "stock": 28,
    },
    
    {
        "id": "prod-13",
        "name": "Linear Switch Sample Pack",
        "description": "Assorted mechanical keyboard switches for testing different typing feels.",
        "price": 24,
        "category": "keyboards",
        "imageUrl": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&auto=format&fit=crop&q=80",
        "stock": 60,
    },
    {
        "id": "prod-14",
        "name": "Dual Monitor Arm Mount",
        "description": "Adjustable gas-spring monitor arm for cleaner desk space and better posture.",
        "price": 129,
        "category": "monitor-accessories",
        "imageUrl": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&auto=format&fit=crop&q=80",
        "stock": 10,
    },
    {
        "id": "prod-15",
        "name": "Tech Organizer Cable Pouch",
        "description": "Portable pouch for storing chargers, dongles, SSDs, and USB cables.",
        "price": 38,
        "category": "desk-setup",
        "imageUrl": "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=400&auto=format&fit=crop&q=80",
        "stock": 33,
    },
    {
        "id": "prod-16",
        "name": "Silent Tactile Switches x90",
        "description": "Quiet pre-lubed tactile switches for silent mechanical keyboard builds.",
        "price": 58,
        "category": "keyboards",
        "imageUrl": "https://images.unsplash.com/photo-1626908013351-800ddd734b8a?w=400&auto=format&fit=crop&q=80",
        "stock": 20,
    },
    {
        "id": "prod-17",
        "name": "Tempered Glass Mouse Pad",
        "description": "Fast low-friction glass surface for smooth and accurate mouse movement.",
        "price": 69,
        "category": "mouse-pads",
        "imageUrl": "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=400&auto=format&fit=crop&q=80",
        "stock": 14,
    },
    {
        "id": "prod-18",
        "name": "Compact Laptop Stand",
        "description": "Foldable aluminum laptop stand for better airflow and ergonomic viewing height.",
        "price": 45,
        "category": "monitor-accessories",
        "imageUrl": "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&auto=format&fit=crop&q=80",
        "stock": 24,
    },
    {
        "id": "prod-19",
        "name": "Barebone CNC Aluminum 65% Keyboard Kit",
        "description": "Premium hot-swappable keyboard kit ready for switches and keycaps.",
        "price": 165,
        "category": "keyboards",
        "imageUrl": "https://images.unsplash.com/photo-1630839437035-dac17da580d0?w=400&auto=format&fit=crop&q=80",
        "stock": 9,
    },
    {
        "id": "prod-20",
        "name": "Ceramic Gaming Mouse Feet",
        "description": "Replacement low-friction mouse skates for faster and smoother glide.",
        "price": 19,
        "category": "mice",
        "imageUrl": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80",
        "stock": 80,
    },
]

CATEGORIES = [
    {"id": "all", "name": "All", "slug": "all"},
    {"id": "keyboards", "name": "Keyboards", "slug": "keyboards"},
    {"id": "mice", "name": "Mice", "slug": "mice"},
    {"id": "mouse-pads", "name": "Mouse Pads", "slug": "mouse-pads"},
    {"id": "cables-hubs", "name": "Cables & Hubs", "slug": "cables-hubs"},
    {"id": "monitor-accessories", "name": "Monitor Accessories", "slug": "monitor-accessories"},
    {"id": "webcams-mics", "name": "Webcams & Mics", "slug": "webcams-mics"},
    {"id": "desk-setup", "name": "Desk Setup", "slug": "desk-setup"},
]
